/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teamrevenger.screenshottool;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;


/**
 *
 * @author thesid01
 * @author rakshak
 * @author rohan
 */
public class MainFrame extends javax.swing.JFrame {

    ArrayList<JLabel> lab1;
    private final LatestScreenShots ScreenShotName;
    private boolean loaded;
    public ScreenShot screenShot = new ScreenShot();
/**
     * Creates new form MainFrame
     */
    
    public MainFrame() {
        this.loaded = false;
        this.ScreenShotName = new LatestScreenShots();
        this.lab1 = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        Gallery = new javax.swing.JFrame();
        GalleryPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        dragCrop = new javax.swing.JFrame();
        cropImageLabel = new javax.swing.JLabel();
        ParentPanel = new javax.swing.JPanel();
        ToolBarPanel = new javax.swing.JPanel();
        captureButton = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        crop = new javax.swing.JButton();
        Share = new javax.swing.JPanel();
        MiddlePanel = new javax.swing.JPanel();
        ImageContainerPanel = new javax.swing.JPanel();
        ImageLabel = new javax.swing.JLabel();
        LastPanel = new javax.swing.JPanel();
        GalleryButton = new javax.swing.JPanel();
        CheckGalleryButton = new javax.swing.JButton();
        SPane = new javax.swing.JPanel();
        MainMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        Open = new javax.swing.JMenuItem();
        Save = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        EditMenu = new javax.swing.JMenu();

        Gallery.setTitle("Gallery");
        Gallery.setMinimumSize(new java.awt.Dimension(800, 600));

        GalleryPanel.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("Screen Shots Taken By ScreenShot App");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout GalleryPanelLayout = new javax.swing.GroupLayout(GalleryPanel);
        GalleryPanel.setLayout(GalleryPanelLayout);
        GalleryPanelLayout.setHorizontalGroup(
            GalleryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GalleryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GalleryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        GalleryPanelLayout.setVerticalGroup(
            GalleryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GalleryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        double width = screenSize.getWidth();
        double height = screenSize.getHeight();
        //Gallery.setSize(width, height);
        ArrayList<String> s = ScreenShotName.getLatestScreenShotName();
        String[] str = new String[s.size()];
        str = s.toArray(str);
        Arrays.sort(str,Collections.reverseOrder());
        jPanel1.removeAll();
        repaint();
        try{
            int i=0;
            int j=0;
            for(String st : str){
                System.out.println(st + "sid");
                Image img;
                img = ImageIO.read(new FileInputStream(st));
                float ratio = img.getWidth(null)/img.getHeight(null);
                img  = img.getScaledInstance(140, (int) (140/ratio), Image.SCALE_DEFAULT);
                ImageIcon icon1=new ImageIcon(img);
                //        i++;
                JLabel tmp = new JLabel();
                tmp.setIcon(icon1);
                tmp.setSize(new Dimension(150,100));
                tmp.setLocation(j*200+10, i*170+10);
                jPanel1.add(tmp);
                if((j+2)*110>width){
                    i++;
                    j=0;
                }else{
                    j++;
                }
            }
        }catch (IOException ex){
            System.err.println(ex);
        }

        javax.swing.GroupLayout GalleryLayout = new javax.swing.GroupLayout(Gallery.getContentPane());
        Gallery.getContentPane().setLayout(GalleryLayout);
        GalleryLayout.setHorizontalGroup(
            GalleryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GalleryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GalleryLayout.setVerticalGroup(
            GalleryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GalleryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dragCrop.setCursor(new java.awt.Cursor(java.awt.Cursor.SW_RESIZE_CURSOR));
        dragCrop.setMinimumSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout dragCropLayout = new javax.swing.GroupLayout(dragCrop.getContentPane());
        dragCrop.getContentPane().setLayout(dragCropLayout);
        dragCropLayout.setHorizontalGroup(
            dragCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cropImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        dragCropLayout.setVerticalGroup(
            dragCropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cropImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        setExtendedState(JFrame.MAXIMIZED_BOTH);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(10, 0, 102));
        setMinimumSize(new java.awt.Dimension(800, 600));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        ToolBarPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        captureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captureButtonActionPerformed(evt);
            }
        });

        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        crop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cropActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ToolBarPanelLayout = new javax.swing.GroupLayout(ToolBarPanel);
        ToolBarPanel.setLayout(ToolBarPanelLayout);
        ToolBarPanelLayout.setHorizontalGroup(
            ToolBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolBarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(ToolBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(captureButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Refresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        ToolBarPanelLayout.setVerticalGroup(
            ToolBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolBarPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(captureButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Refresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(crop)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        try{
            Image img = ImageIO.read(new FileInputStream("resources/scissor.png"));
            captureButton.setIcon(new ImageIcon(img));
            System.out.println("Image fetched");
        }catch(Exception ex){
            System.out.println(ex);
        }
        try{
            Image refreshimg = ImageIO.read(new FileInputStream("resources/refresh.png"));
            Refresh.setIcon(new ImageIcon(refreshimg));
            System.out.println("Image fetched");
        }catch(Exception ex){
            System.out.println(ex);
        }
        try{
            Image cropimg = ImageIO.read(new FileInputStream("resources/crop.png"));
            crop.setIcon(new ImageIcon(cropimg));
            System.out.println("Image fetched");
        }catch(Exception ex){
            System.out.println(ex);
        }

        javax.swing.GroupLayout ShareLayout = new javax.swing.GroupLayout(Share);
        Share.setLayout(ShareLayout);
        ShareLayout.setHorizontalGroup(
            ShareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ShareLayout.setVerticalGroup(
            ShareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        ImageLabel.setBackground(new java.awt.Color(255, 255, 255));
        ImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageLabel.setMaximumSize(new java.awt.Dimension(400, 400));
        ImageLabel.setMinimumSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout ImageContainerPanelLayout = new javax.swing.GroupLayout(ImageContainerPanel);
        ImageContainerPanel.setLayout(ImageContainerPanelLayout);
        ImageContainerPanelLayout.setHorizontalGroup(
            ImageContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImageContainerPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(ImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        ImageContainerPanelLayout.setVerticalGroup(
            ImageContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImageContainerPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(ImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout MiddlePanelLayout = new javax.swing.GroupLayout(MiddlePanel);
        MiddlePanel.setLayout(MiddlePanelLayout);
        MiddlePanelLayout.setHorizontalGroup(
            MiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiddlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImageContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        MiddlePanelLayout.setVerticalGroup(
            MiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiddlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImageContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        LastPanel.setBackground(new java.awt.Color(255, 255, 255));

        CheckGalleryButton.setText("Check Out Gallery");
        CheckGalleryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckGalleryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GalleryButtonLayout = new javax.swing.GroupLayout(GalleryButton);
        GalleryButton.setLayout(GalleryButtonLayout);
        GalleryButtonLayout.setHorizontalGroup(
            GalleryButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CheckGalleryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GalleryButtonLayout.setVerticalGroup(
            GalleryButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CheckGalleryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout SPaneLayout = new javax.swing.GroupLayout(SPane);
        SPane.setLayout(SPaneLayout);
        SPaneLayout.setHorizontalGroup(
            SPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        SPaneLayout.setVerticalGroup(
            SPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout LastPanelLayout = new javax.swing.GroupLayout(LastPanel);
        LastPanel.setLayout(LastPanelLayout);
        LastPanelLayout.setHorizontalGroup(
            LastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GalleryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LastPanelLayout.setVerticalGroup(
            LastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LastPanelLayout.createSequentialGroup()
                .addComponent(GalleryButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        refreshThumbnail();

        javax.swing.GroupLayout ParentPanelLayout = new javax.swing.GroupLayout(ParentPanel);
        ParentPanel.setLayout(ParentPanelLayout);
        ParentPanelLayout.setHorizontalGroup(
            ParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParentPanelLayout.createSequentialGroup()
                .addComponent(ToolBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MiddlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LastPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Share, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ParentPanelLayout.setVerticalGroup(
            ParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParentPanelLayout.createSequentialGroup()
                .addGroup(ParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ToolBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ParentPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MiddlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(LastPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Share, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        //SPane.getViewport().setOpaque(false);

        FileMenu.setText("File");
        FileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMenuActionPerformed(evt);
            }
        });

        Open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        Open.setText("Open");
        Open.setBorderPainted(true);
        Open.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        FileMenu.add(Open);

        Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        FileMenu.add(Save);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        FileMenu.add(Exit);

        MainMenuBar.add(FileMenu);

        EditMenu.setText("Edit");
        MainMenuBar.add(EditMenu);

        setJMenuBar(MainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void captureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_captureButtonActionPerformed
        // TODO add your handling code here:
        setExtendedState(JFrame.ICONIFIED);
        screenShot.takeScreenShot();
        this.loaded = true;
        try {
            Image img;
            img = this.screenShot.getScreenShot(this.screenShot.getLastName());
            this.drawScreenShot(img);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        SPane.removeAll();
        repaint();
        this.refreshThumbnail();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_captureButtonActionPerformed

        
    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        String str = this.screenShot.getLastName();
        System.out.println("siddharth");
        if(this.loaded == true)
            this.resizeScreenShot(str);
    }//GEN-LAST:event_formComponentResized

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            var file = fileChooser.getSelectedFile();
            Image img;
            try {
                screenShot.setLastScreenShotName(file.getAbsolutePath());
                img = screenShot.getScreenShot(file.getAbsolutePath());
                this.drawScreenShot(img);
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("File Opened" + file.getAbsolutePath());
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_OpenActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveActionPerformed

    private void FileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileMenuActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(null,
                                "Are you sure you want to close this window?", "Close Window?",
                                JOptionPane.YES_NO_OPTION);
                        if (reply == JOptionPane.YES_OPTION)
                            System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void CheckGalleryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckGalleryButtonActionPerformed
        // TODO add your handling code here:
        
        Gallery.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Gallery.setLocationRelativeTo(null); // this method display the JFrame to center position of a screen                
        Gallery.setVisible(true); // set
    }//GEN-LAST:event_CheckGalleryButtonActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        this.refreshThumbnail();
    }//GEN-LAST:event_RefreshActionPerformed

    private void cropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cropActionPerformed
        // TODO add your handling code here:
        String name = this.screenShot.getLastName();
        Sketch.cropFunction(name);
        this.screenShot.setLastScreenShotName("cropped"+name);
//        this.drawScreenShot();
//        dragCrop.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//        dragCrop.setLocationRelativeTo(null); // this method display the JFrame to center position of a screen                
//        dragCrop.setVisible(true);
    }//GEN-LAST:event_cropActionPerformed

    // Close JFrame from exit button
    public void drawScreenShot(Image img){
        try{
//            String size = img.getWidth(null) + "x" + img.getHeight(null);
            float ratio =  (float)img.getWidth(null)/(float)img.getHeight(null);
            Image newImage ;
            if(ImageLabel.getSize().height > ImageLabel.getSize().width){
                newImage = img.getScaledInstance((int) ((ImageLabel.getSize().height)/ratio), ImageLabel.getSize().height , Image.SCALE_DEFAULT);

            }else{
                newImage = img.getScaledInstance(ImageLabel.getSize().width, (int) (ImageLabel.getSize().width/ratio), Image.SCALE_DEFAULT);
//                newImage = img.getScaledInstance((int) ((this.getWidth()-400)), (int) ((this.getWidth()-400)/ratio), Image.SCALE_DEFAULT);
            }
            ImageLabel.setIcon(new ImageIcon(newImage));
//            ImageLabel.setText(size);
            System.out.println("Image fetched");
        }catch(Exception ex){
            System.out.println(ex);
        }
    }
    
    void resizeScreenShot(String name){
        try{
            Image img = this.screenShot.getScreenShot(name);
//            String size = img.getWidth(null) + "x" + img.getHeight(null);
            float ratio =  (float)img.getWidth(null)/(float)img.getHeight(null);
            Image newImage ;
            if(ImageLabel.getSize().height > ImageLabel.getSize().width){
                newImage = img.getScaledInstance((int) ((ImageLabel.getSize().height)/ratio), ImageLabel.getSize().height , Image.SCALE_DEFAULT);

            }else{
                newImage = img.getScaledInstance(ImageLabel.getSize().width, (int) (ImageLabel.getSize().width/ratio), Image.SCALE_DEFAULT);
//                newImage = img.getScaledInstance((int) ((this.getWidth()-400)), (int) ((this.getWidth()-400)/ratio), Image.SCALE_DEFAULT);
            }
            this.ImageLabel.setIcon(new ImageIcon(newImage));
//            this.ImageLabel.setText(size);
            System.out.println("Image Resized");
        }catch(IOException ex){
            System.out.println(ex);
        }
    }
    
    void refreshThumbnail(){
        ArrayList<String> s = ScreenShotName.getLatestScreenShotName();
        String[] str = new String[s.size()];
        str = s.toArray(str); 
        Arrays.sort(str,Collections.reverseOrder());
        SPane.removeAll();
        repaint();
        try{
            int i=0;
            for(String st : str){
                Image img;
                img = ImageIO.read(new FileInputStream(st));
                float ratio = img.getWidth(null)/img.getHeight(null);
                if((140/ratio) <=0){
                    ratio = img.getHeight(null)/img.getWidth(null);
                    img  = img.getScaledInstance((int) (140/ratio), (int) (140), Image.SCALE_DEFAULT);
                }else{
                    img  = img.getScaledInstance(140, (int) (140/ratio), Image.SCALE_DEFAULT);
                }
                ImageIcon icon1=new ImageIcon(img);
                JLabel tmp = new JLabel();
                tmp.setIcon(icon1);
                tmp.setSize(new Dimension(150,100));
                tmp.setLocation(0, i*110);
                SPane.add(tmp);
                i++;
                if(i>=5)
                    break;
            }
        }catch (IOException ex){
            System.err.println(ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // create main frame
            MainFrame frame = new MainFrame();
            //center Main Frame
            frame.setTitle("Screen Shot Tool"); //set title
            
            frame.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                    int reply = JOptionPane.showConfirmDialog(null,
                            "Are you sure you want to close this window?", "Close Window?",
                            JOptionPane.YES_NO_OPTION);
                    if (reply == JOptionPane.YES_OPTION)
                        System.exit(0);
                }
            });
            
            frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            frame.setLocationRelativeTo(null); // this method display the JFrame to center position of a screen
            frame.setVisible(true); // set visible;
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckGalleryButton;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JFrame Gallery;
    private javax.swing.JPanel GalleryButton;
    private javax.swing.JPanel GalleryPanel;
    private javax.swing.JPanel ImageContainerPanel;
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JPanel LastPanel;
    private javax.swing.JMenuBar MainMenuBar;
    private javax.swing.JPanel MiddlePanel;
    private javax.swing.JMenuItem Open;
    private javax.swing.JPanel ParentPanel;
    private javax.swing.JButton Refresh;
    private javax.swing.JPanel SPane;
    private javax.swing.JMenuItem Save;
    private javax.swing.JPanel Share;
    private javax.swing.JPanel ToolBarPanel;
    private javax.swing.JButton captureButton;
    private javax.swing.JButton crop;
    private javax.swing.JLabel cropImageLabel;
    private javax.swing.JFrame dragCrop;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
